hina:
  eaglee:
    dolphin:
      host: http://localhost:8080
      token: 123456
      endpoints:
        listWorkflowDefinition: /api/v1/endpoint2
        getTaskDefinitionByWorkflowId: /api/v1/endpoint1
