hina:
  eaglee:
    dolphin:
      host: http://10.0.20.25:12345/dolphinscheduler
      token: 299e2f1483fd6c0718cecc4db06a74cc
      endpoints:
        listWorkflowDefinition: projects/%s/process-definition?pageSize=50&pageNo=1
        getTaskDefinitionByProjectId: projects/%s/task-definition?pageSize=10&pageNo=1
      monitors:
        #回溯监控
        tracebackMonitor:
          enable: true
          project-code:
          cron: 0 * * * * ?

