hina:
  eaglee:
    dolphin:
      host: http://10.0.20.25:12345/dolphinscheduler
      token: 299e2f1483fd6c0718cecc4db06a74cc
      endpoints:
        listWorkflowDefinition: projects/%s/process-definition?pageSize=50&pageNo=1
        getTaskDefinitionByProjectId: projects/%s/task-definition?pageSize=10&pageNo=1
        getTaskLogByTaskInstanceId: https://ds.xunxin-ai.com/dolphinscheduler/log/detail?taskInstanceId=%s&limit=10000&skipLineNum=0
      monitors:
        #回溯监控
#        tracebackMonitor:
#          enable: true
#          project-code: 11986638487424
#          cron: 0/30 * * * * ?
#          status: FAILED,RUNNING
#          #interval-time: 10000000
#          test-mode: true
#          #mock-setting:
        yarnMonitor:
          enable: true
          project-code: 11986638487424
          cron: 0/30 * * * * ?
          status: RUNNING
          #interval-time: 10000000
          test-mode: true

      analyses:
        log-analysis:
          enable: true
          model: deepseek-chat
          temperature: 1.3
          system-prompt: 你是一个数据分析师，你需要根据任务执行日志分析任务执行情况，并给出任务执行结果的分析报告。
          user-prompt: 你是一个数据分析师，你需要根据任务执行日志分析任务执行情况，并给出任务执行结果的分析报告。
